---
title: "CIS 351 Final Project"
author: "Carter Altman"
format:
    html:
        embed-resources: true
---

```{r}
library(tidyverse)
library(janitor)
library(tinytable)
library(ggpubr)
```

# Import Data

```{r}
water_quality <- read_csv("https://raw.githubusercontent.com/caltman05/water_quality_data_analysis/refs/heads/main/data_9.csv")

water_quality
```

# Data Cleaning and Preprocessing

```{r}
water_quality <- water_quality |>
  clean_names()

water_quality
```

```{r}
water_quality <- water_quality |>
  filter(turbidity_ntu <= 50)

water_quality
```

```{r}
water_quality <- water_quality |>
  mutate(
    turbidity_category = case_when(
      turbidity_ntu < 5  ~ "Low",
      turbidity_ntu <= 50 ~ "Moderate",
      turbidity_ntu > 50 ~ "High"
    )
  )

water_quality
```

```{r}
summary(water_quality)
```

# Descriptive Statistics

## Numerical Variables

```{r}
water_quality_statistics <- water_quality |>
  summarize(
    mean_turbidity = mean(turbidity_ntu, na.rm = TRUE),
    median_turbidity = median(turbidity_ntu, na.rm = TRUE),
    sd_turbidity = sd(turbidity_ntu, na.rm = TRUE),
    mean_fecal = mean(fecal_coliform_cfu, na.rm = TRUE),
    median_fecal = median(fecal_coliform_cfu, na.rm = TRUE),
    sd_fecal = sd(fecal_coliform_cfu, na.rm = TRUE),
    mean_chlorophyll = mean(chlorophyll_nu_l, na.rm = TRUE),
    median_chlorophyll = median(chlorophyll_nu_l, na.rm = TRUE),
    sd_chlorophyll = sd(chlorophyll_nu_l, na.rm = TRUE),
    mean_oil = mean(refined_oil_rfu, na.rm = TRUE),
    median_oil = median(refined_oil_rfu, na.rm = TRUE),
    sd_oil = sd(refined_oil_rfu, na.rm = TRUE),
    mean_temp = mean(temp_c, na.rm = TRUE),
    median_temp = median(temp_c, na.rm = TRUE),
    sd_temp = sd(temp_c, na.rm = TRUE),
    n = n(),
    .by = site
  ) |>
  tt(theme = "striped")

water_quality_statistics
```

## Categorical Variables

```{r}
table(water_quality$site)
table(water_quality$turbidity_category)
```

# Data Visualization

```{r}
plot_turbidity_hist <- water_quality |>
  ggplot(aes(x = turbidity_ntu)) +
  geom_histogram(
    binwidth = 2,
    color = "blue",
    fill = "skyblue"
  ) +
  labs(
    title = "Distribution of Turbidity",
    x = "Turbidity (NTU)",
    y = "Count"
  )

plot_turbidity_hist
```

```{r}
plot_turbidity_site <- water_quality |>
  ggplot(aes(x = site, y = turbidity_ntu, fill = site)) +
  geom_boxplot() +
  theme_bw() +
  labs(
    title = "Turbidity by Site",
    x = "Site",
    y = "Turbidity (NTU)"
  )

plot_turbidity_site
```

```{r}
plot_turbidity_oil <- water_quality |>
  ggplot(aes(x = turbidity_ntu, y = refined_oil_rfu)) +
  geom_point() +
  geom_smooth(
    method = "lm",
    color = "blue",
    se = FALSE
  ) +
  stat_regline_equation(
    label.x = 2,
    label.y = 58
  ) +
  stat_cor(
    label.x = 2,
    label.y = 55
  ) +
  labs(
    title = "Turbidity vs Refined Oil",
    x = "Turbidity (NTU)",
    y = "Refined Oil (RFU)"
  )

plot_turbidity_oil
```

```{r}
plot_turbidity_category_site <- water_quality |>
  filter(!is.na(turbidity_category), !is.na(site)) |>
  ggplot(aes(x = site, fill = turbidity_category)) +
  geom_bar() +
  labs(
    title = "Turbidity Category by Site",
    x = "Site",
    y = "Count",
    fill = "Turbidity Category"
  )

plot_turbidity_category_site
```

